apiVersion: v1
kind: Service
metadata:
  name: happy-paws-frontend-service
  namespace: default
spec:
  selector:
    app: happy-paws-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007  # Specify a port in the range 30000-32767
  type: NodePort
