- name: Deploy to Kubernetes
  hosts: localhost
  tasks:
    - name: Create Kubernetes deployment
      community.kubernetes.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        state: present
        definition: "{{ lookup('file', 'k8s/deployment.yaml') }}"
