- name: Deploy to Kubernetes
  hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - name: Create Kubernetes deployment
      community.kubernetes.k8s:
        kubeconfig: "{{ lookup('env', 'KUBECONFIG') }}"
        state: present
        definition: "{{ lookup('file', lookup('env', 'WORKSPACE') ~ '/k8s/deployment.yaml') }}"
